# Paths
prompt_path: "prompt_for_finding_proposals.txt"
api_key_path: "api_key.txt"

# API settings
model: "gpt-4o-mini-2024-07-18"
role: "system"
response_format: "json_object" # "json_object" or null for text

# Generation settings
temperature: 0.0
max_tokens: 1000
top_p: 1.0
frequency_penalty: 0.0
presence_penalty: 0.0
