# Paths
system_prompt_file_name: "system_prompt_for_finding_gender_emails.txt"
user_prompt_file_name: "user_prompt_for_finding_gender_emails.txt"
api_key_file_name: "api_key.txt"

# API settings
model: "gpt-4o-mini-2024-07-18"
response_format: "json_object" # "json_object" or null for text

# Generation settings
temperature: 0.0
max_tokens: 1000
top_p: 1.0
frequency_penalty: 0.0
presence_penalty: 0.0